# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  group1:
    <<: *default
    database: db/group1.sqlite3
  group2:
    <<: *default
    database: db/group2.sqlite3

test:
  group1:
    <<: *default
    database: db/group1.sqlite3
  group2:
    <<: *default
    database: db/group2.sqlite3
